import { AddressBook, Check, Package, UserCircle } from "@phosphor-icons/react";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { AccountSidebar } from "../components/AccountSidebar.jsx";
import { Breadcrumb } from "../components/Breadcrumb.jsx";
import { useStore } from "../context/StoreContext.jsx";
import { assetUrl, useDocumentMeta } from "../lib/format.js";

export function AccountPage() {
  const { accountLoggedIn, setAccountLoggedIn } = useStore();
  const [register, setRegister] = useState(false);
  const location = useLocation();
  useDocumentMeta("My Account", "Manage your MODEX account, orders and sell requests.");
  if (!accountLoggedIn) return <main className="account-auth"><div className="account-auth-image"><img src={assetUrl("hero.webp")} alt="Oxblood luxury bag still life" /></div><div className="account-auth-form"><Link className="checkout-logo" to="/">MODEX</Link><p className="eyebrow">{register ? "CREATE AN ACCOUNT" : "WELCOME BACK"}</p><h1>{register ? "Join MODEX" : "Sign in"}</h1><p>{register ? "Save pieces, follow orders and manage your selling requests." : "Access your orders, wishlist and selling requests."}</p><form onSubmit={(event) => { event.preventDefault(); setAccountLoggedIn(true); }}>{register && <div className="form-grid"><label>First name<input required /></label><label>Last name<input required /></label></div>}<label>Email address<input required type="email" defaultValue="collector@modex.ae" /></label><label>Password<input required type="password" defaultValue="modex2026" /></label><button className="button button-dark button-block" type="submit">{register ? "CREATE ACCOUNT" : "SIGN IN"}</button></form><button className="text-button" onClick={() => setRegister(!register)}>{register ? "Already have an account? Sign in" : "New to MODEX? Create an account"}</button><small>Demo credentials are pre-filled for this prototype.</small></div></main>;
  const segment = location.pathname.split("/").pop();
  return <main className="standard-page page-shell"><Breadcrumb items={[{ label: "Account" }]} /><div className="account-heading"><p className="eyebrow">MY MODEX</p><h1>Welcome, Amelie.</h1></div><div className="account-layout"><AccountSidebar /><section className="account-content">{segment === "account" && <AccountOverview />}{segment === "orders" && <Orders />}{segment === "profile" && <Profile />}{segment === "addresses" && <Addresses />}{segment === "selling" && <Selling />}</section></div></main>;
}

function AccountOverview() { return <><h2>Account overview</h2><div className="overview-grid"><Link to="/account/orders"><Package size={24} /><span><strong>Orders</strong>1 active order</span><b>→</b></Link><Link to="/wishlist"><Check size={24} /><span><strong>Wishlist</strong>View saved pieces</span><b>→</b></Link><Link to="/account/addresses"><AddressBook size={24} /><span><strong>Addresses</strong>1 saved address</span><b>→</b></Link><Link to="/account/selling"><UserCircle size={24} /><span><strong>Sell requests</strong>Track your evaluations</span><b>→</b></Link></div><div className="recent-order"><div><p className="eyebrow">RECENT ORDER · MX-10482</p><h3>Preparation in progress</h3><p>Final quality control · Estimated dispatch 26 August</p></div><img src={assetUrl("oxblood-woven-bag.webp")} alt="Bottega V Jodie Mini" /></div></>; }
function Orders() { return <><h2>Your orders</h2><article className="order-row"><img src={assetUrl("oxblood-woven-bag.webp")} alt="" /><div><p className="eyebrow">ORDER MX-10482 · 24 AUG 2026</p><h3>Bottega V · Jodie Mini</h3><p>Final quality control</p></div><strong>AED 7,950</strong><button className="button button-outline">VIEW DETAILS</button></article></>; }
function Profile() { return <><h2>Profile</h2><form className="luxury-form compact-form"><div className="form-grid"><label>First name<input defaultValue="Amelie" /></label><label>Last name<input defaultValue="Laurent" /></label><label>Email<input type="email" defaultValue="collector@modex.ae" /></label><label>Phone<input defaultValue="+971 50 000 0000" /></label></div><button className="button button-dark">SAVE CHANGES</button></form></>; }
function Addresses() { return <><h2>Addresses</h2><article className="address-card"><p className="eyebrow">DEFAULT</p><h3>Amelie Laurent</h3><p>Business Bay<br />Dubai, United Arab Emirates<br />+971 50 000 0000</p><button className="text-button">Edit address</button></article><button className="button button-outline">ADD NEW ADDRESS</button></>; }
function Selling() { return <><h2>Sell requests</h2><div className="form-success subtle"><span><Check size={22} /></span><h3>No active evaluations.</h3><p>When you submit a piece, its review status will appear here.</p><Link className="button button-outline" to="/sell">SELL WITH US</Link></div></>; }
